image: node:latest

stages:
  - lint
  - flow
  - test
  - release

cache:
  paths:
    - node_modules/

lint:
  stage: lint
  script:
    - yarn install --pure-lockfile
    - yarn lint

flow:
  stage: flow
  script:
    - yarn install --pure-lockfile
    - yarn flow check

test:
  stage: test
  script:
    - yarn install --pure-lockfile
    - yarn test

release:
  stage: release
  variables:
    GH_TOKEN: $GH_TOKEN
    NPM_TOKEN: $NPM_TOKEN
  script:
    - yarn install --pure-lockfile
    - yarn build
    - GH_TOKEN=$GH_TOKEN NPM_TOKEN=$NPM_TOKEN yarn semantic-release
  only:
    - master

